### ISSUE TITLE
question about test

### ISSUE THREAD

**Issue by JUSTM0VE0N** [zhi-xuan-chen/IJCAI-2022_SpanConv#1]
Hello, thanks for your work! I would like to ask why the results of testing with your code are visually almost identical to LMS images？

![(U8XH_O 9N@H)POHGW38UV2](https://user-images.githubusercontent.com/121370263/229278064-474015cd-4e08-44cd-82e6-784b17e56176.png)

**Comment by JUSTM0VE0N** [comment]
On the left is the original LMS image, and on the right is the image fused with your method.

**Comment by zhi-xuan-chen** [comment]
Do you sure you show the right image? If you are sure, can I provide the code
        of my work in your project.
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/1/2023 17:32
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)
        
      
    
  
  
On the left is the original LMS image, and on the right is the image fused with your method.

**Comment by JUSTM0VE0N** [comment]
I just tested it again and found that the results were the same, I used the WV-3 dataset provided by your team for training and testing.

**Comment by zhi-xuan-chen** [comment]
Can you provide your code?  Otherwise I don't know how to help you.
        
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/1/2023 17:30
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)
        
      
    
  
  
Hello, thanks for your work! I would like to ask why the results of testing with your code are visually almost identical to LMS images？

**Comment by JUSTM0VE0N** [comment]
This is the code for training and testing。


| |
isliuch
|
|
***@***.***
|
---- Replied Message ----
| From | Zhi-Xuan ***@***.***> |
| Date | 4/1/2023 18:40 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1) |













Can you provide your code?  Otherwise I don't know how to help you.





***@***.***





---- Replied Message ----





From


***@***.***>





Date


4/1/2023 17:30




To




***@***.***>






Cc



***@***.***>






Subject


[zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)





Hello, thanks for your work! I would like to ask why the results of testing with your code are visually almost identical to LMS images？

**Comment by JUSTM0VE0N** [comment]
Thank you very much, I have sent the code to your email

**Comment by zhi-xuan-chen** [comment]
I am sorry, where is your code? I can not find it in the attachment.







                       
Original Email
                       
                     

Sender:"laxio"< ***@***.*** &gt;;

Sent Time:2023/4/1 18:53

To:"zhi-xuan-chen/IJCAI-2022_SpanConv"< ***@***.*** &gt;;

Cc recipient:"Zhi-Xuan Chen"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue#1)




 
Thank you very much, I have sent the code to your email
 
&mdash;

**Comment by JUSTM0VE0N** [comment]
| |
isliuch
|
|
***@***.***
|
---- Replied Message ----
| From | Zhi-Xuan ***@***.***> |
| Date | 4/6/2023 22:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1) |

I am sorry, where is your code? I can not find it in the attachment.








Original Email



Sender:"laxio"< ***@***.*** &gt;;

Sent Time:2023/4/1 18:53

To:"zhi-xuan-chen/IJCAI-2022_SpanConv"< ***@***.*** &gt;;

Cc recipient:"Zhi-Xuan Chen"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue#1)





Thank you very much, I have sent the code to your email

&mdash;

**Comment by JUSTM0VE0N** [comment]
Did you not receive it, I just sent it again, the name of the compressed package is 'code4 train and test.zip'

**Comment by zhi-xuan-chen** [comment]
It seems that .zip file doesn't exist in your email.
    
        
            
        
    
    
     
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/6/2023 22:17
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Zhi-Xuan ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)
        
      
    
  
  




| |
isliuch
|
|
***@***.***
|
---- Replied Message ----
| From | Zhi-Xuan ***@***.***> |
| Date | 4/6/2023 22:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1) |

I am sorry, where is your code? I can not find it in the attachment.








Original Email



Sender:"laxio"< ***@***.*** &gt;;

Sent Time:2023/4/1 18:53

To:"zhi-xuan-chen/IJCAI-2022_SpanConv"< ***@***.*** &gt;;

Cc recipient:"Zhi-Xuan Chen"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue#1)





Thank you very much, I have sent the code to your email

&mdash;

**Comment by JUSTM0VE0N** [comment]
| |
isliuch
|
|
***@***.***
|
---- Replied Message ----
| From | Zhi-Xuan ***@***.***> |
| Date | 4/6/2023 22:26 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1) |









It seems that .zip file doesn't exist in your email.











---- Replied Message ----





From


***@***.***>





Date


4/6/2023 22:17




To




***@***.***>






Cc



Zhi-Xuan ***@***.***>
,


***@***.***>






Subject


Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)









| |
isliuch
|
|
***@***.***
|
---- Replied Message ----
| From | Zhi-Xuan ***@***.***> |
| Date | 4/6/2023 22:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1) |

I am sorry, where is your code? I can not find it in the attachment.








Original Email



Sender:"laxio"< ***@***.*** &gt;;

Sent Time:2023/4/1 18:53

To:"zhi-xuan-chen/IJCAI-2022_SpanConv"< ***@***.*** &gt;;

Cc recipient:"Zhi-Xuan Chen"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue#1)





Thank you very much, I have sent the code to your email

&mdash;

**Comment by JUSTM0VE0N** [comment]
Sorry to bother you，can you see both .py files?

**Comment by zhi-xuan-chen** [comment]
I am afraid not.
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/6/2023 22:31
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Zhi-Xuan ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zhi-xuan-chen/IJCAI-2022_SpanConv] question about test (Issue #1)
        
      
    
  
  
Sorry to bother you，can you see both .py files?

**Comment by JUSTM0VE0N** [comment]
I sent it to your school email, can you see it in this way?
